pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // Xposed API 依赖仓库
        maven { url 'https://api.xposed.info/' }
    }
}

rootProject.name = "HotspotChannelFix"
include ':app'
